### ISSUE TITLE
Entity does not exists & less than 1 undefined

### ISSUE THREAD

**Issue by DunklerPhoenix** [custom-cards/check-button-card#20]
Heho.
I have two problems.

![iO5FHFHOLr](https://user-images.githubusercontent.com/1261305/95612442-adde5000-0a63-11eb-9f00-09457b8d6c99.png)

```
type: 'custom:vertical-stack-in-card'
cards:
  - entity: vacuum.kartoffelsauger
    type: 'custom:vacuum-card'
    image: default
    compact_view: false
  - type: 'custom:check-button-card'
    title: Filter reinigen
    entity: sensor.kartoffelsauger_filter_cleanup
    color: Green
    width: 50%
    text: day(s)
    severity:
      - value: 3 days
        color: Yellow
      - value: 7 days
        color: Red
  - type: 'custom:check-button-card'
    title: Filter austauschen
    entity: sensor.kartoffelsauger_filter_replace
    color: Green
    width: 50%
    text: day(s)
    severity:
      - value: 50 days
        color: Yellow
      - value: 60 days
        color: Red
  - type: 'custom:check-button-card'
    title: Vordere Rolle reinigen
    entity: sensor.kartoffelsauger_frontroll_cleanup
    color: Green
    width: 50%
    text: day(s)
    severity:
      - value: 12 days
        color: Yellow
      - value: 14 days
        color: Red
  - type: 'custom:check-button-card'
    title: Vordere Rolle tauschen
    entity: sensor.kartoffelsauger_frontroll_replace
    color: Green
    width: 50%
    text: day(s)
    severity:
      - value: 10 months
        color: Yellow
      - value: 12 months
        color: Red
  - type: 'custom:check-button-card'
    title: Sensoren reinigen
    entity: sensor.kartoffelsauger_sensor_cleanup
    color: Green
    width: 50%
    text: day(s)
    severity:
      - value: 25 days
        color: Yellow
      - value: 30 days
        color: Red
  - type: 'custom:check-button-card'
    title: Aufnahmerollen reinigen
    entity: sensor.kartoffelsauger_cleanuprolls_cleanup
    color: Green
    width: 50%
    text: day(s)
    severity:
      - value: 75 days
        color: Yellow
      - value: 90 days
        color: Red
  - type: 'custom:check-button-card'
    title: Aufnahmerollen ersetzen
    entity: sensor.kartoffelsauger_cleanuprolls_replace
    color: Green
    width: 50%
    text: day(s)
    severity:
      - value: 8 months
        color: Yellow
      - value: 9 months
        color: Red
```

The first one is the creation of Entities. The entered sensor entities does not exists thats correct, then I click on "Create" and the bar becomes green, but after a reload its blue with this message again.

What can I do against this?

The second problem is that the text shows "less than 1 undefined" even after I entered the "text" value. Is this problem related to the first?

Greetings
Marco

**Comment by shinn5112** [comment]
I am having the same exact issue. It appears that an MQTT entry is created, however, the time stamp is invalid. This is my config
```yaml
type: 'custom:check-button-card'
title: Brushes
entity: sensor.naomi_brushes
text: month(s)
color: Green
severity:
  - value: 6 months
    color: Red
  - value: 4 months
    color: Yellow

```

This is the corresponding MQTT data that is sent when I click the button 

```json
{
"timestamp_friendly":"Invalid Date",
"severity":[
    {
      "value":"6 months",
      "color":"Red",
      "seconds":15778476
    },
    {
      "value":"4 months",
      "color":"Yellow",
      "seconds":10518984
    }
  ]
}
```

Any suggestions?
