### ISSUE TITLE
Broken functionality after updating to HASS 2021.12.0

### ISSUE THREAD

**Issue by syphernl** [custom-cards/check-button-card#23]
After upgrading to HASS 2021.12.0 all of the `check-button-card` entities now show:

![image](https://user-images.githubusercontent.com/639906/145690941-9ee96d16-c72f-48f0-8f6c-fa85f91dde16.png)

There have been some MQTT breaking changes but they are regarding fans.

The sensor itself shows up as:

![image](https://user-images.githubusercontent.com/639906/145690966-e18e5d89-f01c-4fd9-86dd-9c9b6c7be1b5.png)

There is a timestamp, yet it is not being rendered properly?

**Comment by tech165** [comment]
I have the same problem on my side, the logs look like this : 

> 
2021-12-12 20:54:06 WARNING (MainThread) [homeassistant.components.mqtt.sensor] Invalid state message '{"timestamp":1639360446,"timestamp_friendly":"12/12/2021, 8:54:06 PM","timeout":"18 days","timeout_timestamp":1640915646,"timeout_seconds":1555200,"severity":[{"color":"#bf4060","value":"-3 days","seconds":-259200},{"color":"#bfb540","value":"0 days","seconds":0}]}' from 'homeassistant/sensor/vacuum_maint_clean_contacts/state'

Thanks

**Comment by richie-svk** [comment]
> After upgrading to HASS 2021.12.0 all of the `check-button-card` entities now show:
> 
> ![image](https://user-images.githubusercontent.com/639906/145690941-9ee96d16-c72f-48f0-8f6c-fa85f91dde16.png)
> 
> There have been some MQTT breaking changes but they are regarding fans.
> 
> The sensor itself shows up as:
> 
> ![image](https://user-images.githubusercontent.com/639906/145690966-e18e5d89-f01c-4fd9-86dd-9c9b6c7be1b5.png)
> 
> There is a timestamp, yet it is not being rendered properly?

same issue here, thanks for raising it.

**Comment by rpitera** [comment]
Could it be related to this breaking change?  
https://github.com/home-assistant/core/pull/60269

**Comment by skank01** [comment]
This is indeed very annoying, anyone can fix this?
Is this card still maintained?

**Comment by sir106** [comment]
also waiting for a fix... unfortunatly this plugin seems no longer maintained...

**Comment by hathalud** [comment]
@sir106 It's a bit early to declare that. By the looks of it the developer updates it sporadically every couple of months. My guess is that the dev hasn't updated to the newest version of HA and doesn't know it has breaking changes.

**Comment by ChrisRomp** [comment]
I've got a fix working locally. I just need to finish it so it can handle the old format when broken and save using the new format. I hope to get some time to work on it tomorrow and I'll issue a PR for this repo (if no one else does beforehand), but I can give some instructions at that time as to how to apply the fix to your local install until this is updated officially.

In my house we rely on these cards a lot for chore reminders.  I should've tested before updating. 😅

**Comment by ChrisRomp** [comment]
I've submitted the PR and hopefully this can get tested and merged.  It's TypeScript so you can't just grab the file and drop it into your Home Assistant module folder, however here's the transpiled output if you want to test this locally:

https://gist.github.com/ChrisRomp/b1fe0b714cdc701de0147760afaf7c20

Test at your OWN RISK. I've only tested this in my instance, but it seems to be working for me.  To apply this, go to your `www/community/check-button-card` folder (assuming installed using HACS) and back up the existing `check-button-card.js` file, then replace its contents with the script linked in the [gist](https://gist.github.com/ChrisRomp/b1fe0b714cdc701de0147760afaf7c20).

You may have to hard refresh (i.e., shift+refresh) the web page a few times or clear your cache to pick up the new file. Sometimes a restart of HA can help.  You'll know it's working if the values are displayed, but you can also check the developer tools console and look for:
```
CHECK-BUTTON-CARD
Version: 1.3.0
```

**Comment by sir106** [comment]
> I've submitted the PR and hopefully this can get tested and merged. It's TypeScript so you can't just grab the file and drop it into your Home Assistant module folder, however here's the transpiled output if you want to test this locally:
> 
> https://gist.github.com/ChrisRomp/b1fe0b714cdc701de0147760afaf7c20
> 
> Test at your OWN RISK. I've only tested this in my instance, but it seems to be working for me. To apply this, go to your `www/community/check-button-card` folder (assuming installed using HACS) and back up the existing `check-button-card.js` file, then replace its contents with the script linked in the [gist](https://gist.github.com/ChrisRomp/b1fe0b714cdc701de0147760afaf7c20).
> 
> You may have to hard refresh (i.e., shift+refresh) the web page a few times or clear your cache to pick up the new file. Sometimes a restart of HA can help. You'll know it's working if the values are displayed, but you can also check the developer tools console and look for:
> 
> ```
> CHECK-BUTTON-CARD
> Version: 1.3.0
> ```

Hey Chris, 

you made my day! just installed your fix - and it's working again! thanks for sharing.... very nice that you shared your work...

took me a little to get it work:
- replaced check-button-card.js in www\community\check-button-card with v130
- updated check-button-card.gz in the same folder with new version
- restarted server in the frontend (Settings/Settings/Restart Server)

maybe the steps are obvious...

**Comment by ChrisRomp** [comment]
All good, @sir106. Mine worked fine without needing to swap out the .gz file but YMMV.

**Comment by hathalud** [comment]
> I've submitted the PR and hopefully this can get tested and merged. It's TypeScript so you can't just grab the file and drop it into your Home Assistant module folder, however here's the transpiled output if you want to test this locally:
> 
> https://gist.github.com/ChrisRomp/b1fe0b714cdc701de0147760afaf7c20
> 
> Test at your OWN RISK. I've only tested this in my instance, but it seems to be working for me. To apply this, go to your `www/community/check-button-card` folder (assuming installed using HACS) and back up the existing `check-button-card.js` file, then replace its contents with the script linked in the [gist](https://gist.github.com/ChrisRomp/b1fe0b714cdc701de0147760afaf7c20).
> 
> You may have to hard refresh (i.e., shift+refresh) the web page a few times or clear your cache to pick up the new file. Sometimes a restart of HA can help. You'll know it's working if the values are displayed, but you can also check the developer tools console and look for:
> 
> ```
> CHECK-BUTTON-CARD
> Version: 1.3.0
> ```

Might need to fork this and take over the project if you're willing to... I just noticed that the original dev hasn't updated this code in over a year. I thought the Dev updated it back in Aug, but apparently that was last year.

**Comment by boelle** [comment]
> check the developer tools console and look for:

i could not find that, developer tools yes but no console

did find the card under hacs and frontend, but even after restart of ha it still shows old info

> You may have to hard refresh (i.e., shift+refresh) the web page a few times

did not help, tried incognito too

**Comment by rpitera** [comment]
@ChrisRomp - worked a treat.  I duplicated the steps in @sir106 post and everything is back to working order again.  Thank you very much!

**Comment by boelle** [comment]
had to clear cache

:-D

**Comment by ChrisRomp** [comment]
@Gluwc, @jeremywillans, and @DrJeff are all contributors on the repo, so hopefully one of them can take a look. Let's give them a little time before trying to fork it out. This is part of a bigger collection custom HA cards so it'd be a shame to split them up.

I'm happy to talk about a limited contributor role as well. I, too, don't have a ton of time but I was motivated to fix this because I use the heck out of it.

**Comment by ChrisRomp** [comment]
Thanks @Gluwc!  I'm trying to see if we can whip up a HA script that will force update the relevant entities to the new format and we can remove the bit from this where it'll just handle the old format while leaving its state as "unknown." That would be a breaking change, however so up to y'all.

**Comment by ChrisRomp** [comment]
Since this patch doesn't actually fix the entity states in Home Assistant (only in the card), you can fix them individually by updating them with the check-button-card, or you can bulk update the old entities with this script:

```yaml
alias: Check-Button-Card Update Timestamp Format
mode: single
icon: mdi:calendar-check-outline
sequence:
  - repeat:
      count: '{{ integration_entities("mqtt") | count }}'
      sequence:
        - variables:
            e: '{{integration_entities("mqtt")[repeat.index - 1] }}'
        - condition: template
          value_template: '{{ is_state(e, "unknown") and state_attr(e, "device_class") == "timestamp" and is_number(state_attr(e, "timestamp")) }}'
        - service: logbook.log
          data: 
            name: Check-Button-Card Update Timestamp Format
            message: '{{ "Updating format for " ~ e ~ "." }}'
            entity_id: '{{ e }}'
            domain: sensor
        - service: mqtt.publish
          data:
            topic_template: '{{ "homeassistant/" ~ e.replace(".", "/") ~ "/state" }}'
            payload_template: '{{ states[e].attributes | replace("''timestamp'':", "''timestamp'': ''" ~ (state_attr(e, "timestamp") | as_datetime()).isoformat() ~ "'', ''timestamp_unix'':") | replace("''", ''\"'') }}'
            qos: 0
            retain: true
            # Optionally you can set retain to false to test the result of this,
            # and restarting your MQTT server will reset them to the old value/format
```

As noted in the script comment, if you want to test this first without risking losing your data, you can set the `retain` value to `false` and see how it behaves in HA. You can also adjust the `value_template` of the condition to further filter down the items you wish to update.
