### ISSUE TITLE
Feature request: have support for 'entities' next to 'entity'

### ISSUE THREAD

**Issue by decramy** [custom-cards/check-button-card#29]
It would be nice to have support for multiple entities in stead of only one. The configuration for all given entities gets to be the same; they all get the same timeout/severity/... (or with #28 in place it will be retrieved per entity).

With both issues in place I could make this work:
```
type: custom:auto-entities
card:
  type: custom:check-button-card
filter:
  include:
    - entity_id: sensor.task_*
sort:
  method: attribute
  attribute: timeout_timestamp
```

Thanks so much!
