### ISSUE TITLE
Seperate color for when the due timer is over?

### ISSUE THREAD

**Issue by recklessnl** [custom-cards/check-button-card#8]
First of all, love this card! Thanks for your work.

1) Would it be possible to add a seperate color to when a sensor is over due? I currently have this setup:

```
        - type: custom:check-button-card
          title: Filters status
          entity: sensor.replace_filters
          height: 100px
          timeout: 4 weeks
          due: true
          color: green
          severity:
            - value: 7 days
              color: Yellow
            - value: 1 month
              color: Green
          text: 
            due_in: Needs to replaced in
            over_by: Replace the filters, since
```

But after it becomes over due, the color stays at yellow, when I really want it at red. It would be helpful to have a specific color for when it's overdue.

2) Are there other colors values too like Dark Yellow? Or perhaps a way to do specific RGB values as well? That would certainly be handy.
